# Auto-suggested from drawing titles. VERIFY against HO00 before trusting.
SYSTEM_NAMES = {
    "00": "Plant-wide / Interconnections",
    "13": "Dgn-Md",
    "20": "Aibel As",
    "21": "Wpi9X",
    "24": "Zeqz",
    "27": "Qdpo",
    "42": "Scd/Titleblock",
    "43": "Sfwu",
    "45": "Qdpo",
    "50": "Seq. No",
    "53": "Ctsl",
    "56": "Disc./Doc.Type",
    "62": "Gkef-",
    "63": "Scd/Titleblock",
    "64": "Scd/Titleblock",
    "65": "Disc./Doc.Type",
    "71": "Disc./Doc.Type",
    "72": "Scd/Titleblock",
    "77": "Scd/Titleblock",
    "79": "Disc./Doc.Type",
    "82": "Scd/Titleblock",
    "85": "Scd/Titleblock",
}