"""
src/graf_qa.py — Streamlit page: Plant Q&A (GraphRAG).

Ask the whole plant in plain language; the answer is computed from the merged
DEXPI graph + tag register, NOT generated by a chatbot. Every tag in the answer
is real. An optional AI layer only rephrases the retrieved facts.

Registered in nav_pages.py. Engine: src/analysis/graph_qa.py (also a CLI).
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

# explicit: the GEMINI_API_KEY gates below depend on .env, and Streamlit does
# not auto-load it. Must run before any os.getenv("GEMINI_API_KEY") check —
# same pattern as hazop.py (a page reached directly wouldn't see the key
# otherwise).
load_dotenv()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ui import page_header
from analysis.graph_qa import (build_plant_graph, ask, phrase_with_llm,
                               llm_understand, understand_prompt, phrase_prompt)

try:
    from config import PID_DIR
    RAW = str(Path(PID_DIR).parent)
except Exception:                                                  # noqa: BLE001
    RAW = "data/raw"

_EXAMPLES = [
    "What is downstream of 27-PT4805?",
    "What protects 24-XV2163A?",
    "How is 27-PT4805 connected to 27-XV4814?",
    "List all PSVs",
    "What trips close 20-XV2008?",
    "What is in the same loop as 24-XV2163A?",
    "How many transmitters in system 27?",
]
_BADGE = {
    "downstream": "⬇️ downstream", "upstream": "⬆️ upstream",
    "neighbors": "🔗 neighbours", "path": "🧭 path", "protects": "🛡️ safeguards",
    "trips_closing": "🚨 trips", "loop": "🔁 loop", "section": "🗂️ section",
    "list_type": "📋 list", "unknown": "❓",
}


@st.cache_resource(show_spinner="Merging DEXPI drawings into one plant graph…")
def _model():
    return build_plant_graph(RAW)


page_header("Plant Q&A",
            "Ask the plant in plain language — AI interprets the question, the "
            "DEXPI graph answers, and every tag is verified against the register")
st.caption("Retrieval over structure, not free-form generation: the answer is "
           "COMPUTED from the merged DEXPI graph and tag register, and every "
           "tag it returns is real. AI (Gemini) is used at the EDGES only — to "
           "interpret a free-form question into a structured query, and to "
           "rephrase the retrieved facts — and every tag it proposes is verified "
           "against the register before the graph answers. It invents nothing; "
           "the graph is the source of truth. Draft for review, not authoritative.")

M = _model()
g = M["graph"]
st.caption(f"📊 Plant graph: **{g.number_of_nodes()} tags**, "
           f"**{g.number_of_edges()} connections**, merged from "
           f"{len(M['sections'])} DEXPI drawings.")

st.write("**Try one:**")
cols = st.columns(3)
for i, ex in enumerate(_EXAMPLES):
    if cols[i % 3].button(ex, key=f"ex{i}", use_container_width=True):
        st.session_state["gq"] = ex

q = st.text_input("Ask about the plant",
                  value=st.session_state.get("gq", ""),
                  placeholder="e.g. what protects 27-XV4814?  ·  list all PSVs "
                              "in system 63  ·  what is upstream of 24-LV2162A?")

ans = None
if q:
    # AI understanding (optional): Gemini parses the free-form question into a
    # structured query; every tag it proposes is still verified against the
    # register, and the graph computes the answer. Falls back to the regex
    # parser with no key / on failure.
    hint = None
    if os.getenv("GEMINI_API_KEY"):
        use_ai = st.checkbox(
            "🤖 Let AI interpret the question (handles free-form phrasing — "
            "tags are still verified against the register)", value=True)
        if use_ai:
            with st.spinner("Interpreting the question…"):
                hint = llm_understand(q, M["objects"])

    ans = ask(q, M, hint=hint)
    if hint:
        st.caption(
            f"🤖 AI parsed → intent **{hint.get('intent') or '(fell back)'}**, "
            f"tags **{', '.join(hint.get('tags') or []) or '—'}** — verified "
            f"against the register before the graph answered.")
    st.markdown(f"### {_BADGE.get(ans.intent, '')}")
    st.markdown(ans.text)

    if ans.tags:
        with st.expander(f"🔎 Grounding — {len(ans.tags)} real tag(s) this "
                         f"answer rests on"):
            objs = M["objects"]
            st.dataframe(
                [{"tag": t, "type": getattr(objs.get(t), "type_code", "") or "—",
                  "system": getattr(objs.get(t), "system", "") or "—",
                  "category": getattr(objs.get(t), "category", "") or "—"}
                 for t in ans.tags[:200]],
                use_container_width=True, hide_index=True)
        st.caption("Every tag above exists in the merged DEXPI register — the "
                   "answer is verifiable by construction.")

    if os.getenv("GEMINI_API_KEY"):
        if st.button("✍️ Rephrase with AI (grounded in the facts above)"):
            with st.spinner("Phrasing…"):
                out = phrase_with_llm(q, ans)
            if out:
                st.info(out)
                st.caption("The model was given ONLY the retrieved facts and "
                           "told to invent nothing; the deterministic answer "
                           "above is the source of truth.")
            else:
                st.caption("AI rephrase unavailable — the answer above stands.")
    else:
        st.caption("Set GEMINI_API_KEY to enable an AI rephrase of the answer — "
                   "the graph answer above works without it.")

# -------------------------------------------------------------- prompt viewer
st.divider()
with st.expander("🔍 See the exact prompt(s) sent to the AI"):
    st.caption("Full transparency: this is verbatim what Gemini receives. The "
               "AI only interprets the question and rephrases the retrieved "
               "facts — the DEXPI graph computes the answer, and every tag is "
               "verified against the register.")
    _demo_q = q or "what protects 27-XV4814?"
    st.markdown("**1 · Understand** — free-form question → structured query "
                "(JSON): the tags it returns are re-checked against the "
                "register, so a hallucinated tag is dropped.")
    st.code(understand_prompt(_demo_q), language="text")
    st.markdown("**2 · Rephrase** — turn the graph's retrieved facts into fluent "
                "text, inventing nothing:")
    if ans is not None:
        st.code(phrase_prompt(_demo_q, ans), language="text")
    else:
        st.caption("Ask a question above to see the rephrase prompt populated "
                   "with that question's retrieved facts.")
